export const CHANGE_TYPE = 'CHANGE_TYPE';
export const MODIFY_TYPE = 'MODIFY_TYPE';
export const FETCH_TYPE_FAILED = 'FETCH_TYPE_FAILED';

export const PURCHASE_CASE_SUCCESS = 'PURCHASE_CASE_SUCCESS';
export const PURCHASE_CASE_FAIL = 'PURCHASE_BURGER_FAIL';
