export const CHANGE_TYPE = 'CHANGE_TYPE';
export const MODIFY_TYPE = 'MODIFY_TYPE';
export const FETCH_TYPE_FAILED = 'FETCH_TYPE_FAILED';

export const PURCHASE_CASE_START = 'PURCHASE_CASE_START';
export const PURCHASE_CASE_SUCCESS = 'PURCHASE_CASE_SUCCESS';
export const PURCHASE_CASE_FAIL = 'PURCHASE_CASE_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
